version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-1.15
      - test-1.15-32bit
      - test-1.16
      - test-1.16-32bit

jobs:
  test-1.15:
    docker:
      - image: 'circleci/golang:1.15'
    environment:
      - GO_TEST_FLAGS: -race
    steps: &ref_0
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: sudo apt-get install -y python3-pip
      - run: pip3 install opcua
      - run: go test -v $GO_TEST_FLAGS ./...
      - run: go test -v -tags=integration ./uatest
      - run: go install ./...
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  test-1.16:
    docker:
      - image: 'circleci/golang:1.16'
    environment:
      - GO_TEST_FLAGS: -race
    steps: *ref_0
  test-1.15-32bit:
    docker:
      - image: 'circleci/golang:1.15'
    environment:
      - GOARCH: 386
    steps: *ref_0
  test-1.16-32bit:
    docker:
      - image: 'circleci/golang:1.16'
    environment:
      - GOARCH: 386
    steps: *ref_0
