version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-1.10
      - test-1.11
jobs:
  test-1.10:
    docker:
      - image: 'circleci/golang:1.10'
    working_directory: /go/src/github.com/wmnsk/gopcua
    steps: &ref_0
      - checkout
      - run: go get -u github.com/pkg/errors
      - run: go get -u github.com/google/go-cmp/cmp
      - run: go install ./...
      - run: go get -v -t -d ./...
      - run: go get -u golang.org/x/lint/golint
      - run: golint ./...
      - run: go test -v ./...
  test-1.11:
    docker:
      - image: 'circleci/golang:1.11'
    working_directory: /go/src/github.com/wmnsk/gopcua
    steps: *ref_0
